# Generated by Django 4.1.10 on 2023-08-30 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_alter_historicalteam_language_alter_team_language"),
        ("problems", "0004_problemstatement_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("received_time", models.DurationField()),
                ("solved_time", models.DurationField(blank=True, null=True)),
                ("solve_duration", models.DurationField(blank=True, null=True)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="+",
                        to="problems.problem",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="users.team",
                    ),
                ),
            ],
        ),
    ]
