# Generated by Django 5.1.5 on 2025-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0005_problemstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="number",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
