# Generated by Django 5.1.5 on 2025-02-03 16:42

from django.db import migrations


def migrate_problem_numbers(apps, schema_editor):
    Problem = apps.get_model("problems", "Problem")

    for p in Problem.objects.all():
        p.number = int(p.name)
        p.save()


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0006_problem_number"),
    ]

    operations = [
        migrations.RunPython(migrate_problem_numbers),
    ]
