# Generated by Django 5.1.5 on 2025-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0007_auto_20250203_1642"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="problem",
            name="name",
        ),
        migrations.AlterField(
            model_name="problem",
            name="number",
            field=models.PositiveIntegerField(),
        ),
    ]
