# Generated by Django 5.1.5 on 2025-02-03 17:57

from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    SolvedProblem = apps.get_model("problems", "SolvedProblem")

    distinct = SolvedProblem.objects.order_by("team_id", "problem_id").distinct(
        "team_id", "problem_id"
    )
    SolvedProblem.objects.exclude(id__in=distinct).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0008_remove_problem_name_alter_problem_number"),
        ("users", "0031_alter_spanishteamdata_agreement"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AddConstraint(
            model_name="solvedproblem",
            constraint=models.UniqueConstraint(
                models.F("team"),
                models.F("problem"),
                name="solvedproblem__team_problem",
            ),
        ),
    ]
