# Generated by Django 5.1.5 on 2025-02-03 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("problems", "0009_solvedproblem_solvedproblem__team_problem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryProblem",
        ),
    ]
