repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: "1.3.2"
    hooks:
      - id: djade
        args: [--target-version, "5.1"]
