repos:
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      rev: v0.1.13
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format
    - repo: https://github.com/djlint/djLint
      rev: v1.34.1
      hooks:
          - id: djlint-reformat-django
          - id: djlint-django
