version: '3.4'
services:
  bullet-db:
    image: postgres:10-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=bullet
      - POSTGRES_PASSWORD=bullet
      - POSTGRES_DB=bullet
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  bullet-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: basebuild
    image: bullet
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=bullet.settings.development
      - PARENT_HOST=localhost:8000
    ports:
      - "8000:8000"
    volumes:
      - ./bullet/:/usr/src/bullet/
    depends_on:
      - bullet-db
    command: ./entrypoint.sh

volumes:
  postgres_data:
