# Generated by Django 5.1.5 on 2025-06-03 10:59

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models

import gallery.models


class Migration(migrations.Migration):
    replaces = [
        ("gallery", "0001_initial"),
        ("gallery", "0002_photo_image_height_photo_image_width_and_more"),
        ("gallery", "0003_photo_taken_at"),
        ("gallery", "0004_alter_photo_image"),
    ]

    initial = True

    dependencies = [
        ("competitions", "0028_rename_categorycompetition_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        height_field="image_height",
                        upload_to=gallery.models.photo_upload_to,
                        width_field="image_width",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.album",
                    ),
                ),
                (
                    "image_width",
                    models.PositiveIntegerField(),
                ),
                (
                    "image_height",
                    models.PositiveIntegerField(),
                ),
                (
                    "taken_at",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                models.F("competition"),
                name="album__slug_competition",
            ),
        ),
    ]
