# Generated by Django 4.1.10 on 2023-09-03 19:21

import django.db.models.deletion
import django_countries.fields
import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("competitions", "0028_rename_categorycompetition_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("slug", models.SlugField(max_length=256)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["country", "title"],
            },
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    pictures.models.PictureField(
                        aspect_ratios=[None],
                        breakpoints={
                            "l": 1200,
                            "m": 992,
                            "s": 768,
                            "xl": 1400,
                            "xs": 576,
                        },
                        container_width=1200,
                        file_types=["WEBP"],
                        grid_columns=4,
                        pixel_densities=[1, 2],
                        upload_to="photos",
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="gallery.album",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                models.F("slug"),
                models.F("competition"),
                models.F("country"),
                name="slug_competition_country",
            ),
        ),
    ]
