# Generated by Django 4.1.10 on 2023-09-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="album",
            constraint=models.UniqueConstraint(
                models.F("title"),
                models.F("competition"),
                models.F("country"),
                name="title_competition_country",
            ),
        ),
    ]
