# Generated by Django 4.1.10 on 2023-12-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_photo_image_height_photo_image_width_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
