# Generated by Django 5.1.5 on 2025-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_photo_taken_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to="photos",
                width_field="image_width",
            ),
        ),
    ]
