# Generated by Django 5.1.5 on 2025-02-05 23:15

from django.db import migrations, models

import gallery.models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_photo_taken_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                upload_to=gallery.models.photo_upload_to,
                width_field="image_width",
            ),
        ),
    ]
