# Generated by Django 5.1.5 on 2025-06-03 09:58

import shutil
from pathlib import Path
from typing import TYPE_CHECKING

from django.db import migrations

from gallery.thumbnails import resize_photo

if TYPE_CHECKING:
    from gallery.models import Photo


def migrate_photos(apps, schema_editor):
    Photo: "Photo" = apps.get_model("gallery", "Photo")

    for photo in Photo.objects.all():
        image_path = Path(photo.image.path)
        if not image_path.exists():
            photo.delete()
            continue

        photo.image.save(image_path.name, photo.image)
        old_dir = image_path.with_suffix("")
        if old_dir.exists():
            shutil.rmtree(old_dir)

        resize_photo(photo)


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0004_alter_photo_image"),
    ]

    operations = [migrations.RunPython(migrate_photos)]
