# Generated by Django 4.1.3 on 2022-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatetemplate",
            name="for_team",
            field=models.BooleanField(default=False),
        ),
    ]
