# Generated by Django 5.0.3 on 2024-04-10 22:12

import django.db.models.deletion
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0032_wildcard_category_alter_wildcard_competition"),
        ("documents", "0003_selfservecertificate_certificatetemplate_self_serve"),
    ]

    operations = [
        migrations.CreateModel(
            name="TexTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("single_team", models.BooleanField(default=False)),
                (
                    "template",
                    models.FileField(upload_to=documents.models.tex_template_upload),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
            ],
        ),
    ]
