# Generated by Django 5.0.3 on 2024-04-11 11:46

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0004_textemplate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="textemplate",
            name="single_team",
        ),
        migrations.AddField(
            model_name="textemplate",
            name="entrypoint",
            field=models.CharField(default="main.tex", max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="textemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("team_multiple", "Multiple teams"),
                    ("team_single", "Single team"),
                    ("generic", "Generic"),
                ],
                default="generic",
                max_length=16,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="TexJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("context", models.JSONField()),
                (
                    "output_file",
                    models.FileField(
                        blank=True, null=True, upload_to=documents.models.tex_job_upload
                    ),
                ),
                ("output_log", models.TextField(blank=True)),
                ("output_error", models.CharField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="documents.textemplate",
                    ),
                ),
            ],
        ),
    ]
