# Generated by Django 5.0.3 on 2024-04-11 12:19

from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "0005_remove_textemplate_single_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="texjob",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="texjob",
            name="context",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="texjob",
            name="output_file",
            field=models.FileField(
                blank=True, default="", upload_to=documents.models.tex_job_upload
            ),
            preserve_default=False,
        ),
    ]
