# Generated by Django 3.2.7 on 2021-11-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grade",
            options={"ordering": ("school_type", "order")},
        ),
        migrations.AlterField(
            model_name="schooltype",
            name="note",
            field=models.CharField(
                blank=True, help_text="shown in admin interface", max_length=32
            ),
        ),
    ]
