# Generated by Django 4.1 on 2022-08-04 21:23

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_auto_20211121_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="country",
            field=django_countries.fields.CountryField(default="SK", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="grade",
            name="school_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="education.schooltype",
            ),
        ),
    ]
