# Generated by Django 4.0.6 on 2022-07-24 11:35

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_auto_20211121_1405"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
            preserve_default=False,
        ),
    ]
