# Generated by Django 4.0.6 on 2022-08-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_school_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="school_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="education.schooltype",
            ),
        ),
    ]
