# Generated by Django 4.0.7 on 2022-09-04 08:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_school_country_alter_grade_school_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="izo",
        ),
        migrations.AddField(
            model_name="school",
            name="importer",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="school",
            name="importer_identifier",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="school",
            name="address",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("importer"),
                django.db.models.expressions.F("importer_identifier"),
                name="school__importer_importer_identifier",
            ),
        ),
    ]
