# Generated by Django 4.0.7 on 2022-09-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0005_schooltype_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="search",
            field=models.TextField(
                blank=True, help_text="used to improve search performance"
            ),
        ),
    ]
