# Generated by Django 4.1.10 on 2023-08-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0006_school_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="importer_ignored",
            field=models.BooleanField(default=False),
        ),
    ]
