# Generated by Django 4.1.10 on 2023-08-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0007_school_importer_ignored"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
    ]
