# Generated by Django 3.2.7 on 2021-11-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0006_alter_wildcard_school"),
        ("education", "0001_initial"),
        ("users", "0002_alter_team_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="school",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="education.school"
            ),
        ),
        migrations.DeleteModel(
            name="School",
        ),
    ]
