# Generated by Django 4.0.4 on 2022-06-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0012_rename_competitionsite_competitionvenue_and_more"),
        ("education", "0002_auto_20211121_1405"),
        ("users", "0005_alter_team_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="competition_site",
            new_name="competition_venue",
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={
                ("school", "in_school_symbol"),
                ("competition_venue", "number"),
            },
        ),
    ]
