# Generated by Django 4.0.5 on 2022-06-16 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0002_auto_20211121_1405"),
        ("competitions", "0013_rename_competitionsite_competitionvenue_and_more"),
        ("users", "0005_alter_team_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="competition_site",
            new_name="competition_venue",
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={
                ("competition_venue", "number"),
                ("school", "in_school_symbol"),
            },
        ),
    ]
