# Generated by Django 4.0.6 on 2022-07-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_school_country"),
        ("users", "0006_rename_competition_site_team_competition_venue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="is_official",
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="in_school_symbol",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.school",
            ),
        ),
    ]
