# Generated by Django 4.1 on 2022-08-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0003_school_country_alter_grade_school_type"),
        ("users", "0006_rename_competition_site_team_competition_venue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="graduation_year",
        ),
        migrations.RemoveField(
            model_name="team",
            name="is_official",
        ),
        migrations.AddField(
            model_name="participant",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="education.grade",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="in_school_symbol",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="education.school",
            ),
        ),
    ]
