# Generated by Django 4.0.6 on 2022-08-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0004_alter_grade_school_type"),
        ("users", "0007_remove_team_is_official_team_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="graduation_year",
        ),
        migrations.AddField(
            model_name="participant",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="education.grade",
            ),
        ),
    ]
