# Generated by Django 4.1.1 on 2022-09-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_team_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="consent_photos",
            field=models.BooleanField(default=False),
        ),
    ]
