# Generated by Django 4.1.1 on 2022-09-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_contestant_rename_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contestant",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contestants",
                to="users.team",
            ),
        ),
    ]
