# Generated by Django 4.1.1 on 2022-09-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_contestant_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestant",
            name="birth_year",
        ),
    ]
