# Generated by Django 4.1.1 on 2022-09-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_team_consent_photos"),
        ("users", "0011_remove_contestant_birth_year"),
    ]

    operations = []
