# Generated by Django 4.1.1 on 2022-09-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_merge_20220917_1403"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="approved_at",
        ),
        migrations.AddField(
            model_name="team",
            name="is_waiting",
            field=models.BooleanField(default=False),
        ),
    ]
