# Generated by Django 4.1.1 on 2022-09-20 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_remove_team_approved_at_team_is_waiting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
