# Generated by Django 4.1.1 on 2022-09-30 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_school_search"),
        ("competitions", "0021_rename_competitionvenue_venue"),
        ("users", "0015_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="team",
            old_name="competition_venue",
            new_name="venue",
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("school", "in_school_symbol"), ("venue", "number")},
        ),
    ]
