# Generated by Django 4.1.1 on 2022-10-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_rename_competition_venue_team_venue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_checked_in",
            field=models.BooleanField(default=False),
        ),
    ]
