# Generated by Django 4.1.2 on 2022-10-25 08:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django_countries.fields
import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0023_remove_categorycompetition_ranking"),
        ("users", "0017_team_is_checked_in"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=128)),
                ("template", models.TextField(blank=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                (
                    "team_countries",
                    web.fields.ChoiceArrayField(
                        base_field=django_countries.fields.CountryField(max_length=2),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "team_languages",
                    web.fields.ChoiceArrayField(
                        base_field=web.fields.LanguageField(
                            choices=[
                                ("af", "Afrikaans"),
                                ("ar", "Arabic"),
                                ("ar-dz", "Algerian Arabic"),
                                ("ast", "Asturian"),
                                ("az", "Azerbaijani"),
                                ("bg", "Bulgarian"),
                                ("be", "Belarusian"),
                                ("bn", "Bengali"),
                                ("br", "Breton"),
                                ("bs", "Bosnian"),
                                ("ca", "Catalan"),
                                ("cs", "Czech"),
                                ("cy", "Welsh"),
                                ("da", "Danish"),
                                ("de", "German"),
                                ("dsb", "Lower Sorbian"),
                                ("el", "Greek"),
                                ("en", "English"),
                                ("en-au", "Australian English"),
                                ("en-gb", "British English"),
                                ("eo", "Esperanto"),
                                ("es", "Spanish"),
                                ("es-ar", "Argentinian Spanish"),
                                ("es-co", "Colombian Spanish"),
                                ("es-mx", "Mexican Spanish"),
                                ("es-ni", "Nicaraguan Spanish"),
                                ("es-ve", "Venezuelan Spanish"),
                                ("et", "Estonian"),
                                ("eu", "Basque"),
                                ("fa", "Persian"),
                                ("fi", "Finnish"),
                                ("fr", "French"),
                                ("fy", "Frisian"),
                                ("ga", "Irish"),
                                ("gd", "Scottish Gaelic"),
                                ("gl", "Galician"),
                                ("he", "Hebrew"),
                                ("hi", "Hindi"),
                                ("hr", "Croatian"),
                                ("hsb", "Upper Sorbian"),
                                ("hu", "Hungarian"),
                                ("hy", "Armenian"),
                                ("ia", "Interlingua"),
                                ("id", "Indonesian"),
                                ("ig", "Igbo"),
                                ("io", "Ido"),
                                ("is", "Icelandic"),
                                ("it", "Italian"),
                                ("ja", "Japanese"),
                                ("ka", "Georgian"),
                                ("kab", "Kabyle"),
                                ("kk", "Kazakh"),
                                ("km", "Khmer"),
                                ("kn", "Kannada"),
                                ("ko", "Korean"),
                                ("ky", "Kyrgyz"),
                                ("lb", "Luxembourgish"),
                                ("lt", "Lithuanian"),
                                ("lv", "Latvian"),
                                ("mk", "Macedonian"),
                                ("ml", "Malayalam"),
                                ("mn", "Mongolian"),
                                ("mr", "Marathi"),
                                ("ms", "Malay"),
                                ("my", "Burmese"),
                                ("nb", "Norwegian Bokmål"),
                                ("ne", "Nepali"),
                                ("nl", "Dutch"),
                                ("nn", "Norwegian Nynorsk"),
                                ("os", "Ossetic"),
                                ("pa", "Punjabi"),
                                ("pl", "Polish"),
                                ("pt", "Portuguese"),
                                ("pt-br", "Brazilian Portuguese"),
                                ("ro", "Romanian"),
                                ("ru", "Russian"),
                                ("sk", "Slovak"),
                                ("sl", "Slovenian"),
                                ("sq", "Albanian"),
                                ("sr", "Serbian"),
                                ("sr-latn", "Serbian Latin"),
                                ("sv", "Swedish"),
                                ("sw", "Swahili"),
                                ("ta", "Tamil"),
                                ("te", "Telugu"),
                                ("tg", "Tajik"),
                                ("th", "Thai"),
                                ("tk", "Turkmen"),
                                ("tr", "Turkish"),
                                ("tt", "Tatar"),
                                ("udm", "Udmurt"),
                                ("uk", "Ukrainian"),
                                ("ur", "Urdu"),
                                ("uz", "Uzbek"),
                                ("vi", "Vietnamese"),
                                ("zh-hans", "Simplified Chinese"),
                                ("zh-hant", "Traditional Chinese"),
                            ],
                            max_length=8,
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "team_statuses",
                    web.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("U", "Unconfirmed"),
                                ("R", "Registered"),
                                ("W", "Waiting list"),
                                ("C", "Checked in"),
                            ],
                            max_length=1,
                        ),
                        blank=True,
                        size=None,
                    ),
                ),
                (
                    "team_contestants",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, size=None
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "excluded_teams",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="users.team"
                    ),
                ),
                (
                    "team_venues",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="competitions.venue"
                    ),
                ),
            ],
        ),
    ]
