# Generated by Django 4.1.2 on 2022-10-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_emailcampaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="last_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
