# Generated by Django 4.1.2 on 2022-10-22 12:13

import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_emailcampaign_last_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="team_statuses",
            field=web.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("U", "Unconfirmed"),
                        ("R", "Registered"),
                        ("W", "Waiting list"),
                        ("C", "Checked in"),
                    ],
                    max_length=1,
                ),
                blank=True,
                size=None,
            ),
        ),
    ]
