# Generated by Django 4.1.2 on 2022-10-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_alter_emailcampaign_team_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="excluded_teams",
            field=models.ManyToManyField(blank=True, related_name="+", to="users.team"),
        ),
    ]
