# Generated by Django 4.1.3 on 2022-11-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_team_online_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="is_disqualified",
            field=models.BooleanField(default=False),
        ),
    ]
