# Generated by Django 4.1.2 on 2022-10-25 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_emailcampaign_excluded_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailcampaign",
            name="team_contestants",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
