# Generated by Django 4.1.4 on 2022-12-29 22:08

import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_team_is_disqualified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailcampaign",
            name="team_statuses",
            field=web.fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("U", "Unconfirmed"),
                        ("R", "Registered"),
                        ("W", "Waiting list"),
                        ("C", "Checked in"),
                        ("K", "Reviewed"),
                        ("D", "Disqualified"),
                    ],
                    max_length=1,
                ),
                blank=True,
                size=None,
            ),
        ),
    ]
