# Generated by Django 4.1.5 on 2023-03-07 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0023_alter_emailcampaign_team_statuses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["number", "id"]},
        ),
    ]
