# Generated by Django 5.0.3 on 2024-04-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_alter_historicalteam_language_alter_team_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalteam",
            name="rank_country",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalteam",
            name="rank_international",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalteam",
            name="rank_venue",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="rank_country",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="rank_international",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="rank_venue",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
