# Generated by Django 5.0.3 on 2024-04-15 13:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_historicalteam_rank_country_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailcampaign",
            options={"ordering": ["-last_sent", "subject"]},
        ),
    ]
