# Generated by Django 6.0.2 on 2026-06-20 21:52

from django.db import migrations, models

import users.validators


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_alter_historicalteam_language_alter_team_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalteam",
            name="contact_email",
            field=models.EmailField(
                max_length=254, validators=[users.validators.validate_email_mx_record]
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="contact_email",
            field=models.EmailField(
                max_length=254, validators=[users.validators.validate_email_mx_record]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254,
                unique=True,
                validators=[users.validators.validate_email_mx_record],
                verbose_name="email address",
            ),
        ),
    ]
