# Generated by Django 4.0.4 on 2022-06-06 12:12

import django.contrib.postgres.fields
import django.db.models.expressions
import django_countries.fields
import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BranchCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    web.fields.BranchField(
                        choices=[
                            (1, "Math Náboj"),
                            (2, "Physics Náboj"),
                            (3, "Náboj Junior"),
                        ]
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("sk", "Slovak"),
                                ("cs", "Czech"),
                                ("en", "English"),
                                ("de", "German"),
                                ("fi", "Finnish"),
                                ("pl", "Polish"),
                                ("hu", "Hungarian"),
                                ("ro", "Romanian"),
                                ("ru", "Russian"),
                                ("uk", "Ukrainian"),
                                ("be", "Belarusian"),
                                ("fa", "Persian"),
                            ],
                            max_length=8,
                        ),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="branchcountry",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("branch"),
                django.db.models.expressions.F("country"),
                name="branch_country_unique",
            ),
        ),
    ]
