# Generated by Django 4.0.5 on 2022-06-15 17:43

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_alter_branchcountry_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchcountry",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="Europe/Bratislava"),
            preserve_default=False,
        ),
    ]
