# Generated by Django 4.0.5 on 2022-06-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0003_alter_branchcountry_languages"),
        ("countries", "0003_branchcountry_timezone"),
    ]

    operations = []
