# Generated by Django 4.0.7 on 2022-09-03 19:20

import django.db.models.deletion
import django.db.models.expressions
import django_countries.fields
import web.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "competitions",
            "0014_remove_categorydescription_category_category_order_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BranchRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    web.fields.BranchField(
                        choices=[
                            (1, "Náboj Math"),
                            (2, "Náboj Physics"),
                            (3, "Náboj Junior"),
                            (4, "Náboj Chemistry"),
                        ]
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BRANCH", "Branch administrator"),
                            ("COUNTRY", "Country administrator"),
                            ("VENUE", "Venue administrator"),
                            ("NONE", "No role"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("can_translate", models.BooleanField(default=False)),
                ("can_delegate", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="competitions.venue",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="branchrole",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("user"),
                django.db.models.expressions.F("branch"),
                name="branch_role__user_branch",
            ),
        ),
    ]
