# Generated by Django 4.1.1 on 2022-09-24 14:23

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "competitions",
            "0018_alter_categorycompetition_max_members_per_team_and_more",
        ),
        ("bullet_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="branchrole",
            old_name="can_translate",
            new_name="is_translator",
        ),
        migrations.RemoveField(
            model_name="branchrole",
            name="can_delegate",
        ),
        migrations.RemoveField(
            model_name="branchrole",
            name="country",
        ),
        migrations.RemoveField(
            model_name="branchrole",
            name="role",
        ),
        migrations.RemoveField(
            model_name="branchrole",
            name="venue",
        ),
        migrations.AddField(
            model_name="branchrole",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="CompetitionRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                ("can_delegate", models.BooleanField(default=False)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competitions.competition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="competitions.venue",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="competitionrole",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("competition"),
                name="competition_role__user_competition",
            ),
        ),
    ]
