# Generated by Django 4.1.1 on 2022-09-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0019_remove_competitionvenue_email_alias_and_more"),
        ("bullet_admin", "0002_rename_can_translate_branchrole_is_translator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionrole",
            name="venue",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="competitions.competitionvenue",
            ),
        ),
    ]
