# Generated by Django 4.1.2 on 2022-10-18 17:56

import django_countries.fields
import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0023_remove_categorycompetition_ranking"),
        ("bullet_admin", "0003_alter_competitionrole_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionrole",
            name="country",
        ),
        migrations.RemoveField(
            model_name="competitionrole",
            name="venue",
        ),
        migrations.AddField(
            model_name="competitionrole",
            name="countries",
            field=web.fields.ChoiceArrayField(
                base_field=django_countries.fields.CountryField(max_length=2),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="competitionrole",
            name="venue_objects",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="competitions.venue"
            ),
        ),
    ]
