# Generated by Django 4.1.2 on 2022-11-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bullet_admin", "0004_remove_competitionrole_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionrole",
            name="is_operator",
            field=models.BooleanField(default=False),
        ),
    ]
