# Generated by Django 4.1.10 on 2023-08-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bullet_admin", "0005_competitionrole_is_operator"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchrole",
            name="is_school_editor",
            field=models.BooleanField(default=False),
        ),
    ]
