# Generated by Django 4.1.10 on 2023-09-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bullet_admin", "0006_branchrole_is_school_editor"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchrole",
            name="is_photograph",
            field=models.BooleanField(default=False),
        ),
    ]
