# Generated by Django 5.2.7 on 2025-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bullet_admin", "0008_remove_branchrole_is_school_editor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="branchrole",
            name="is_photographer",
        ),
        migrations.RemoveField(
            model_name="branchrole",
            name="is_translator",
        ),
        migrations.RemoveField(
            model_name="competitionrole",
            name="can_delegate",
        ),
    ]
