# Generated by Django 3.2.7 on 2021-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
                ('language', models.TextField(choices=[('sk', 'Slovak'), ('cs', 'Czech'), ('en-gb', 'British English'), ('de-ch', 'Swiss German'), ('de-de', 'German'), ('fi', 'Finnish'), ('pl', 'Polish'), ('hu', 'Hungarian'), ('ro', 'Romanian'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('be', 'Belarusian'), ('fa', 'Persian')])),
                ('branch', models.IntegerField(choices=[(1, 'Math'), (2, 'Physics'), (3, 'Junior')])),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
