# Generated by Django 3.2.7 on 2022-05-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_menu'),
        ('web', '0002_page'),
    ]

    operations = [
    ]
