# Generated by Django 4.0.4 on 2022-05-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_merge_0002_menu_0002_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.IntegerField(
                        choices=[(1, "Math"), (2, "Physics"), (3, "Junior")]
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                ("image", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    models.IntegerField(
                        choices=[(1, "Math"), (2, "Physics"), (3, "Junior")]
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                ("image", models.FileField(upload_to="")),
            ],
        ),
    ]
