# Generated by Django 4.0.4 on 2022-05-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_organizer_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
