# Generated by Django 4.0.4 on 2022-05-29 21:23

import competitions.models.competitions
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_organizer_partner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="branch",
            field=competitions.models.competitions.BranchField(
                choices=[
                    (1, "Mathematical Náboj"),
                    (2, "Physics Náboj"),
                    (3, "Náboj Junior"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="organizer",
            name="branch",
            field=competitions.models.competitions.BranchField(
                choices=[
                    (1, "Mathematical Náboj"),
                    (2, "Physics Náboj"),
                    (3, "Náboj Junior"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="branch",
            field=competitions.models.competitions.BranchField(
                choices=[
                    (1, "Mathematical Náboj"),
                    (2, "Physics Náboj"),
                    (3, "Náboj Junior"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="branch",
            field=competitions.models.competitions.BranchField(
                choices=[
                    (1, "Mathematical Náboj"),
                    (2, "Physics Náboj"),
                    (3, "Náboj Junior"),
                ]
            ),
        ),
    ]
