# Generated by Django 4.0.4 on 2022-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_menu_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="order",
            field=models.IntegerField(default=1),
        ),
    ]
