# Generated by Django 4.0.4 on 2022-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_menu_branch_alter_organizer_branch_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="language",
            field=models.TextField(
                choices=[
                    ("sk", "Slovak"),
                    ("cs", "Czech"),
                    ("en", "English"),
                    ("de", "German"),
                    ("fi", "Finnish"),
                    ("pl", "Polish"),
                    ("hu", "Hungarian"),
                    ("ro", "Romanian"),
                    ("ru", "Russian"),
                    ("uk", "Ukrainian"),
                    ("be", "Belarusian"),
                    ("fa", "Persian"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="language",
            field=models.TextField(
                choices=[
                    ("sk", "Slovak"),
                    ("cs", "Czech"),
                    ("en", "English"),
                    ("de", "German"),
                    ("fi", "Finnish"),
                    ("pl", "Polish"),
                    ("hu", "Hungarian"),
                    ("ro", "Romanian"),
                    ("ru", "Russian"),
                    ("uk", "Ukrainian"),
                    ("be", "Belarusian"),
                    ("fa", "Persian"),
                ]
            ),
        ),
    ]
