# Generated by Django 4.0.4 on 2022-06-14 13:57

import django_countries.fields
from django.db import migrations

import web.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_remove_menu_url_remove_page_url_menu_countries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="countries",
            field=web.fields.ChoiceArrayField(
                base_field=django_countries.fields.CountryField(max_length=2), size=None
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="countries",
            field=web.fields.ChoiceArrayField(
                base_field=django_countries.fields.CountryField(max_length=2), size=None
            ),
        ),
    ]
