# Generated by Django 4.0.4 on 2022-06-15 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0015_alter_menu_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="slug",
            new_name="url",
        ),
    ]
