# Generated by Django 4.0.6 on 2022-07-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0016_rename_slug_menu_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Translation",
        ),
    ]
