# Generated by Django 4.1 on 2022-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0017_delete_translation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentblock",
            name="content_block__reference_unique",
        ),
        migrations.AddConstraint(
            model_name="contentblock",
            constraint=models.UniqueConstraint(
                fields=("group", "reference", "branch", "country", "language"),
                name="content_block__reference_unique",
            ),
        ),
    ]
