# Generated by Django 4.1.1 on 2022-09-30 18:23

import django_countries.fields
from django.db import migrations, models

import web.fields
import web.models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0018_remove_contentblock_content_block__reference_unique_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch",
                    web.fields.BranchField(
                        choices=[
                            (1, "Náboj Math"),
                            (2, "Náboj Physics"),
                            (3, "Náboj Junior"),
                            (4, "Náboj Chemistry"),
                        ]
                    ),
                ),
                (
                    "type",
                    models.IntegerField(choices=[(0, "Organizer"), (1, "Partner")]),
                ),
                ("name", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                ("image", models.FileField()),
                (
                    "countries",
                    web.fields.ChoiceArrayField(
                        base_field=django_countries.fields.CountryField(max_length=2),
                        size=None,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Organizer",
        ),
        migrations.DeleteModel(
            name="Partner",
        ),
    ]
