# Generated by Django 4.1.1 on 2022-10-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0019_logo_delete_organizer_delete_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
    ]
