# Generated by Django 5.0.1 on 2024-02-01 21:09

import django.db.models.deletion
from django.db import migrations, models

import web.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0022_alter_contentblock_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "states",
                    web.fields.IntegerChoiceArrayField(
                        base_field=models.IntegerField(
                            choices=[
                                (1, "Before web start"),
                                (2, "Before registration"),
                                (3, "Registration"),
                                (4, "After registration"),
                                (5, "Competition"),
                                (6, "After competition"),
                                (7, "Locked"),
                            ]
                        ),
                        size=None,
                    ),
                ),
                ("order", models.IntegerField()),
                (
                    "block_type",
                    models.IntegerField(
                        choices=[
                            (1, "Logo cloud"),
                            (2, "Text with image on side"),
                            (3, "Grid with icons"),
                            (4, "Competition timeline"),
                            (5, "Main header"),
                            (6, "Markdown text"),
                            (7, "Grid with images"),
                        ]
                    ),
                ),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.page"
                    ),
                ),
            ],
            options={
                "ordering": ["page", "order"],
            },
        ),
    ]
