# Generated by Django 5.1.5 on 2025-01-23 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0023_pageblock"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Logo",
        ),
    ]
