# Generated by Django 3.2.4 on 2021-08-10 14:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0003_alter_localizedproblem_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionsite",
            name="accepted_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sk", "Slovak"),
                        ("cs", "Czech"),
                        ("en-gb", "British English"),
                        ("de-ch", "Swiss German"),
                        ("de-de", "German"),
                        ("fi", "Finnish"),
                        ("pl", "Polish"),
                        ("hu", "Hungarian"),
                        ("ro", "Romanian"),
                        ("ru", "Russian"),
                        ("uk", "Ukrainian"),
                        ("be", "Belarusian"),
                        ("fa", "Persian"),
                    ],
                    max_length=10,
                ),
                size=None,
            ),
        ),
    ]
