# Generated by Django 3.2.4 on 2021-09-26 11:05

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('competitions', '0004_alter_competitionsite_accepted_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
