# Generated by Django 3.2.7 on 2021-11-21 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0004_alter_competitionsite_accepted_languages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorycompetition",
            options={"ordering": ("-category",)},
        ),
    ]
