# Generated by Django 4.0.4 on 2022-06-06 12:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0008_alter_competition_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionsite",
            name="accepted_languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("sk", "Slovak"),
                        ("cs", "Czech"),
                        ("en", "English"),
                        ("de", "German"),
                        ("fi", "Finnish"),
                        ("pl", "Polish"),
                        ("hu", "Hungarian"),
                        ("ro", "Romanian"),
                        ("ru", "Russian"),
                        ("uk", "Ukrainian"),
                        ("be", "Belarusian"),
                        ("fa", "Persian"),
                    ],
                    max_length=10,
                ),
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="localizedproblem",
            name="language",
            field=models.TextField(
                choices=[
                    ("sk", "Slovak"),
                    ("cs", "Czech"),
                    ("en", "English"),
                    ("de", "German"),
                    ("fi", "Finnish"),
                    ("pl", "Polish"),
                    ("hu", "Hungarian"),
                    ("ro", "Romanian"),
                    ("ru", "Russian"),
                    ("uk", "Ukrainian"),
                    ("be", "Belarusian"),
                    ("fa", "Persian"),
                ]
            ),
        ),
    ]
