# Generated by Django 4.0.4 on 2022-06-13 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0010_category_categorydescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorycompetition",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="competitions.category"
            ),
        ),
    ]
