# Generated by Django 4.0.4 on 2022-06-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_team_language"),
        ("address", "0003_auto_20200830_1851"),
        ("competitions", "0011_alter_categorycompetition_category"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetitionSite",
            new_name="CompetitionVenue",
        ),
        migrations.RenameModel(
            old_name="Site",
            new_name="Venue",
        ),
        migrations.RenameField(
            model_name="competitionvenue",
            old_name="site",
            new_name="venue",
        ),
        migrations.AlterUniqueTogether(
            name="competitionvenue",
            unique_together={("category_competition", "venue")},
        ),
    ]
