# Generated by Django 4.0.5 on 2022-06-16 12:39

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0013_rename_competitionsite_competitionvenue_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
            preserve_default=False,
        ),
    ]
