# Generated by Django 4.0.5 on 2022-06-16 14:53

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0014_venue_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("branch"),
                django.db.models.expressions.F("slug"),
                name="category__branch_slug",
            ),
        ),
    ]
