# Generated by Django 4.1.1 on 2022-09-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0015_alter_categorycompetition_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
    ]
