# Generated by Django 4.0.6 on 2022-08-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0015_category_order_category_slug_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoryDescription",
        ),
    ]
