# Generated by Django 4.1.1 on 2022-09-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competitions",
            "0018_alter_categorycompetition_max_members_per_team_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competitionvenue",
            name="email_alias",
        ),
        migrations.AddField(
            model_name="competitionvenue",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
