# Generated by Django 4.1.1 on 2022-09-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bullet_admin", "0003_alter_competitionrole_venue"),
        ("users", "0015_remove_user_username_alter_user_email"),
        ("competitions", "0020_alter_competitionvenue_unique_together_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompetitionVenue",
            new_name="Venue",
        ),
    ]
