# Generated by Django 4.1.1 on 2022-10-01 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0021_rename_competitionvenue_venue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="graduation_year",
        ),
    ]
