# Generated by Django 4.1.1 on 2022-10-04 19:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0022_remove_competition_graduation_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorycompetition",
            name="ranking",
        ),
    ]
