# Generated by Django 4.1.2 on 2022-10-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0024_competition_results_freeze_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
