# Generated by Django 4.1.5 on 2023-02-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0025_venue_is_reviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="competition",
            constraint=models.UniqueConstraint(
                models.F("branch"),
                models.F("number"),
                name="competition_branch_number_unique",
            ),
        ),
    ]
