# Generated by Django 4.1.10 on 2023-08-29 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0026_competition_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ("name", "category_competition__identifier")},
        ),
    ]
