# Generated by Django 4.1.10 on 2023-08-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0008_school_is_hidden"),
        ("problems", "0005_problemstat"),
        ("competitions", "0027_alter_venue_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CategoryCompetition",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="venue",
            options={"ordering": ("name", "category__identifier")},
        ),
        migrations.RemoveConstraint(
            model_name="category",
            name="competitions_category_competition_identifier_unique",
        ),
        migrations.RenameField(
            model_name="venue",
            old_name="category_competition",
            new_name="category",
        ),
        migrations.AlterUniqueTogether(
            name="venue",
            unique_together={("category", "shortcode")},
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                models.F("competition"),
                models.F("identifier"),
                name="competitions_category_identifier_unique",
            ),
        ),
    ]
