# Generated by Django 4.1.10 on 2023-08-31 10:54

import competitions.models.competitions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0028_rename_categorycompetition_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="secret_key",
            field=models.CharField(
                default=competitions.models.competitions.get_random_string,
                max_length=64,
            ),
        ),
    ]
