# Generated by Django 4.1.10 on 2023-09-27 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0029_competition_secret_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="registration_flow_type",
            field=models.IntegerField(
                choices=[(0, "Default"), (1, "Spain (NJ)")], default=0
            ),
        ),
    ]
