# Generated by Django 5.0.3 on 2024-03-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0031_remove_competition_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildcard",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="competitions.category",
            ),
        ),
        migrations.AlterField(
            model_name="wildcard",
            name="competition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="competitions.competition",
            ),
        ),
    ]
