# Generated by Django 5.1 on 2024-12-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0032_wildcard_category_alter_wildcard_competition"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="is_isolated",
            field=models.BooleanField(default=False),
        ),
    ]
