# Generated by Django 5.1.5 on 2025-01-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0033_venue_is_isolated"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="first_problem",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="competition",
            name="problem_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
