# Generated by Django 5.1.5 on 2025-01-23 19:32


from django.db import migrations


def populate_problem_numbers(apps, schema_editor):
    Competition = apps.get_model("competitions", "Competition")
    Category = apps.get_model("competitions", "Category")
    Problem = apps.get_model("problems", "Problem")

    for competition in Competition.objects.all():
        competition.problem_count = Problem.objects.filter(
            competition=competition
        ).count()
        competition.save()

    categories = Category.objects.all().prefetch_related("problems")
    for category in categories:
        problem = category.problems.order_by("number").first()
        if problem:
            category.first_problem = problem.number
            category.save()


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0034_category_first_problem_competition_problem_count"),
    ]

    operations = [migrations.RunPython(populate_problem_numbers)]
