# Generated by Django 5.2.7 on 2025-10-14 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0035_auto_20250123_1932"),
    ]

    operations = [
        migrations.RenameField(
            model_name="venue",
            old_name="participants_hidden",
            new_name="abbreviate_names",
        ),
    ]
