# Generated by Django 6.0.2 on 2026-02-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competitions", "0036_rename_participants_hidden_venue_abbreviate_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="number",
            field=models.IntegerField(),
        ),
    ]
